{{- if eq (include "operator.webhook.enabled" .) "true" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "operator.fullname" . }}-selfsigned
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end -}}
