{{- if .Values.image.pullSecrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-imagepullsecret
  labels:
    {{- include "operator.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "operator.imagePullSecret" .Values.image }}
{{- end -}}

