---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-controller
  labels:
    {{- include "operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io

{{- if eq (include "operator.webhook.enabled" .) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-webhook
  labels:
    {{- include "operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.fullname" . }}-webhook
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-webhook
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
