{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.fullname" . }}-config
  labels:
    {{- include "operator.labels" . | nindent 4 }}
data:
  config.yaml: | {{- .Values.config.values | toYaml | nindent 4 }}
{{- end -}}
