---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-leader-election
  labels:
    {{- include "operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.fullname" . }}-conroller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "operator.fullname" . }}-leader-election
  apiGroup: rbac.authorization.k8s.io
