{{- if .Values.image.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-imagesecret
  labels:
    {{- include "operator.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "operator.imageSecret" .Values.image }}
{{- end -}}

