---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-controller
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      targetPort: {{ .Values.controller.ports.metrics }}
      protocol: TCP
      port: {{ .Values.controller.ports.metrics }}
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}

{{- if eq (include "operator.webhook.enabled" .) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-webhook
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      targetPort: {{ .Values.webhook.ports.metrics }}
      protocol: TCP
      port: {{ .Values.webhook.ports.metrics }}
    - name: server
      targetPort: {{ .Values.webhook.ports.server }}
      protocol: TCP
      port: {{ .Values.webhook.ports.server }}
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
{{- end -}}
