---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.fullname" . }}-controller
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- if eq (include "operator.webhook.enabled" .) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.fullname" . }}-webhook
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
