fullnameOverride: ""

# specify your image detail here
image:
  registry: your-operator-registry-url
  repository: your-operator-repository
  pullPolicy: Always
  tag: "v0.1.0"
  # If enabled, you have to provide secret (username and password) for image pull-push operatoion, 
  # please use a third party tool like helm-secrets and not push your
  # raw credentials to the git repository
  secret:
    enabled: false
    username: ""
    password: ""

# controller configuration settings
controller:
  # rules that your manager service-account needs in runtime
  rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  ports:
    metrics: 8080
    probe: 8081

  # arguments to be passed to the manager container
  arguments:
    - controller
    - --metrics-bind-port=8080
    - --health-probe-bind-port=8081
    - --leader-elect

  # how much resource to be used
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  # security-context within the container
  securityContext:
    capabilities:
      drop:
      - ALL
    allowPrivilegeEscalation: false

# define your webhook detail with appropriate rules
webhook:
  replicas: 1

  # rules that your webhook service-account needs in runtime
  rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "watch"]

  ports:
    metrics: 8080
    probe: 8081
    server: 8443

  # arguments to be passed to the webhook container
  arguments:
    - webhook
    - --metrics-bind-port=8080
    - --health-probe-bind-port=8081
    - --server-bind-port=8443

  mutation:
    enabled: false
    path: "/mutation"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["your-resource-group-with-domian"]
        apiVersions: ["your-resource-version"]
        resources: ["plural-resource-name"]

  validation:
    enabled: true
    path: "/validation"
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["your-resource-group-with-domian"]
        apiVersions: ["your-resource-version"]
        resources: ["plural-resource-name"]

  tls:
    directory: /tmp/secrets

  # how much resource to be used
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  # security-context within the container
  securityContext:
    {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

serviceAccount:
  annotations: {}

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  selector: {}

nodeSelector: {}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
          - arm64
          - ppc64le
          - s390x
        - key: kubernetes.io/os
          operator: In
          values:
          - linux

tolerations: []

# If enabled, the values will be injected to the container
# it can be used as a way to pass application config, also we have
# set RUNNING_INSIDE_POD environemnt inside container as an identifier
config:
  enabled: true
  mountPath: /tmp/operator
  values:
    key: "value"
